eureka:
  client:
    service-url:
      defaultZone: 'http://admin:admin@service-eureka:13100/eureka/'
  instance:
    prefer-ip-address: true


server:
  port: 13600
spring:
  application:
    name: service-project
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://10.215.136.245:3307/bccm?characterEncoding=utf-8&useSSL=false&servertimezone=cst
    username: root
    password: P0eWKBtPky
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    #properties:
    #  hibernate:
    #    default_schema: dbo
    hibernate:
      ddl-auto: update
    show-sql: true
    
#Redis配置
  redis:
    database: 0 # Redis数据库索引（默认为0）
    host: 10.215.136.245  #Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password: sOp.YVg7_a3dh5w1 # Redis服务器连接密码（默认为空）
    timeout: 5000 # 连接超时时间（毫秒）
    jedis:
      pool:
        max-active: -1 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0 # 连接池中的最小空闲连接
