spring:
  security:
    basic:
      enabled: true
    user:
      name: 'admin'
      password: 'admin'

server:
  port: 13100

eureka:
  instance:
    hostname: service-eureka
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: 'http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/'